export { DashboardSkeleton } from './DashboardSkeleton'
export { TableSkeleton } from './TableSkeleton'
export { CardSkeleton } from './CardSkeleton'
export { NotificationsSkeleton } from './NotificationsSkeleton'
export { ReportsSkeleton } from './ReportsSkeleton'
export { ProductsSkeleton } from './ProductsSkeleton'
export { OrdersSkeleton } from './OrdersSkeleton'
export { CustomersSkeleton } from './CustomersSkeleton'
export { CollectionsSkeleton } from './CollectionsSkeleton'
export { CouponsSkeleton } from './CouponsSkeleton'
export { GiftCardsSkeleton } from './GiftCardsSkeleton'
export { PagesSkeleton } from './PagesSkeleton'

